export const GET_PEOPLE = 'GET_PEOPLE'
export const GET_NEXT = 'GET_NEXT'
export const SET_LOADING = 'SET_LOADING'
export const SET_COUNT = 'SET_COUNT '
export const CHAR_LOADING = 'CHAR_LOADING'
export const FILTER = 'FILTER'
